version: '3'

services:

    portfolio:
        container_name: 'portfolio'
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./app:/app
        environment:
            NODE_ENV: develop
        command: gatsby develop --host=0.0.0.0
